install:
	cd consul-master-nodes/consul-cluster; make
	cd worker-nodes/docker-consul-registrator; make
	cd ingress-nodes/lb-haproxy-static-single-service; make
	cd ingress-nodes/lb-traefik-https-proxy; make